name: Label PR and Direct Pushes Based on Changes

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Apply Labels
        uses: actions/github-script@v6
        with:
          script: |
            const patterns = {
              frontend: ['**/*.html', '**/*.css', '**/*.js'],
              images: ['**/*.png', '**/*.jpg', '**/*.jpeg', '**/*.gif', '**/*.svg'],
              backend: ['**/*.py']
            };
            
            const labelMappings = {
              frontend: 'front end',
              images: 'images',
              backend: 'back end'
            };
            
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;
            
            const response = await github.rest.pulls.listFiles({
              owner,
              repo,
              pull_number: prNumber
            });
            
            const files = response.data.map(file => file.filename);
            let labelsToAdd = [];

            for (const [category, filePatterns] of Object.entries(patterns)) {
              const isMatch = files.some(filename => 
                filePatterns.some(pattern => new Minimatch(pattern).match(filename))
              );
              if (isMatch) {
                labelsToAdd.push(labelMappings[category]);
              }
            }
            
            if (labelsToAdd.length > 0) {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: prNumber,
                labels: labelsToAdd
              });
              console.log(`Labels added: ${labelsToAdd.join(', ')}.`);
            } else {
              console.log("No specific changes detected.");
            }
          github-token: ${{secrets.GITHUB_TOKEN}}
