name: HTML Syntax Checker

on:
  push:
    paths:
      - '**/*.html'
  pull_request:
    paths:
      - '**/*.html'

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install html5validator
        run: pip install html5validator
      
      - name: Find Modified HTML Files
        id: modified_files
        run: |
          git fetch origin main:main  # Adjust 'main' if your default branch differs
          CHANGED_FILES=$(git diff --name-only main...HEAD | grep '\.html$')
          echo "::set-output name=modified_html_files::$CHANGED_FILES"
      
      - name: Validate Modified HTML Files
        run: |
          MODIFIED_HTML_FILES="${{ steps.modified_files.outputs.modified_html_files }}"
          if [ -n "$MODIFIED_HTML_FILES" ]; then
            html5validator $MODIFIED_HTML_FILES
          else
            echo "No HTML files have been modified."
          fi

