name: HTML Validation and Testing

on:
  push:
    paths:
      - '**/*.html'
  pull_request:
    paths:
      - '**/*.html'

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install html5validator
        run: pip install html5validator

      - name: Validate HTML files
        run: |
            html5validator --root . \
            --ignore 'Attribute “.*” not allowed on element “.*” at this point.' \
            --ignore 'Bad value “.*” for attribute “href” on element “a”' \
            --ignore 'Text not allowed in element “.*” in this context.'
