name: Label Test Issues

permissions:
    issues: write
    contents: read

on:
  issues:
    types:
        - reopened
        - opened

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Label issue with 'test'
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const title = context.payload.issue.title;
            const body = context.payload.issue.body;
            const testPattern = /\btest(ing)?\b/i; // Regular expression to match "test" or "testing"

            if (testPattern.test(title) || testPattern.test(body)) {
              const issue_number = context.payload.issue.number;
              const owner = context.repo.owner;
              const repo = context.repo.repo;
              
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels: ['test']
              });
            }
