name: Python Application Workflow

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install Flask
      run: pip install Flask 

    - name: Run Python script
      run: python test_login.py
          python 'auto_test/tes_signup_auto.py'
          python 'auto_test/test_createQuiz_auto.py'
          python 'auto_test/test_login_auto.py'
          python 'auto_test/test_quizPage_student_auto.py'
