name: Python Application Workflow

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        pip install Flask
        pip install selenium

    - name: Run Python test script
      run: python test_login.py

    - name: Run Python scripts in auto_test folder
      run: |
        for file in auto_test/*.py; do
          python "$file"
        done
