name: Python Application Workflow

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Setup ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver


    - name: Install dependencies
      run: |
        pip install Flask
        pip install selenium

    - name: Run Python test script
      run: python test_login.py

    - name: Run Python scripts in auto_test folder
      run: |
        for file in auto_test/*.py; do
          python "$file"
        done
