name: Unlabel Issue on Close

on:
  issues:
    types: 
        - closed

jobs:
  unlabelIssue:
    runs-on: ubuntu-latest
    steps:
    - name: Remove Label
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'needs to be done'
          })
